"""
Phase 4b: Apply weather & sea state classifications to database (efficient bulk update).

The original 04_weather_seastate.py stalled doing 37K individual UPDATEs.
This script loads the already-generated JSON classification files and applies
them via temp tables + bulk UPDATE for much better performance.

JSON files (already generated by 04_weather_seastate.py):
  - cleaned/weather_classifications.json
  - cleaned/sea_state_classifications.json
"""

import json
import sqlite3
from pathlib import Path

BASE_DIR = Path("/home/jic823/climate")
OUT_DIR = BASE_DIR / "cleaned"
DB_PATH = OUT_DIR / "cliwoc_cleaned.db"
WEATHER_JSON = OUT_DIR / "weather_classifications.json"
SEA_STATE_JSON = OUT_DIR / "sea_state_classifications.json"


def main():
    print("=" * 70)
    print("PHASE 4b: BULK APPLY WEATHER & SEA STATE CLASSIFICATIONS")
    print("=" * 70)

    # Load JSON mappings
    print("\nLoading classification files ...")
    with open(WEATHER_JSON) as f:
        weather_map = json.load(f)
    with open(SEA_STATE_JSON) as f:
        sea_state_map = json.load(f)

    # Filter to only classified terms
    weather_pairs = [(term, info["category"])
                     for term, info in weather_map.items()
                     if info.get("category")]
    sea_pairs = [(term, info["douglas_scale"])
                 for term, info in sea_state_map.items()
                 if info.get("douglas_scale") is not None]

    print(f"  Weather: {len(weather_pairs):,} classified terms (of {len(weather_map):,})")
    print(f"  Sea state: {len(sea_pairs):,} classified terms (of {len(sea_state_map):,})")

    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    # Ensure columns exist
    for col, typ in [("weather_category", "TEXT"), ("sea_state", "INTEGER")]:
        try:
            cur.execute(f"ALTER TABLE observations ADD COLUMN {col} {typ}")
        except sqlite3.OperationalError:
            pass

    # Clear any partial results from the stalled run
    print("\nClearing partial results from previous run ...")
    cur.execute("UPDATE observations SET weather_category = NULL")
    cur.execute("UPDATE observations SET sea_state = NULL")
    conn.commit()

    # ── Weather: use temp table + bulk UPDATE ──
    print("\nApplying weather classifications via temp table ...")
    cur.execute("CREATE TEMP TABLE weather_map (term TEXT PRIMARY KEY, category TEXT)")
    # Insert in batches of 500
    for i in range(0, len(weather_pairs), 500):
        batch = weather_pairs[i:i+500]
        cur.executemany("INSERT INTO weather_map VALUES (?, ?)", batch)
    conn.commit()

    cur.execute("""
        UPDATE observations
        SET weather_category = (
            SELECT category FROM weather_map WHERE weather_map.term = observations.Weather
        )
        WHERE Weather IN (SELECT term FROM weather_map)
    """)
    weather_updated = cur.rowcount
    conn.commit()
    print(f"  Updated {weather_updated:,} records")

    # ── Sea state: use temp table + bulk UPDATE ──
    print("\nApplying sea state classifications via temp table ...")
    cur.execute("CREATE TEMP TABLE sea_map (term TEXT PRIMARY KEY, scale INTEGER)")
    for i in range(0, len(sea_pairs), 500):
        batch = sea_pairs[i:i+500]
        cur.executemany("INSERT INTO sea_map VALUES (?, ?)", batch)
    conn.commit()

    cur.execute("""
        UPDATE observations
        SET sea_state = (
            SELECT scale FROM sea_map WHERE sea_map.term = observations.StateSea
        )
        WHERE StateSea IN (SELECT term FROM sea_map)
    """)
    sea_updated = cur.rowcount
    conn.commit()
    print(f"  Updated {sea_updated:,} records")

    # ── Create indexes ──
    print("\nCreating indexes ...")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_obs_weather_category ON observations (weather_category)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_obs_sea_state ON observations (sea_state)")
    conn.commit()

    # ── Verification ──
    print("\n── Verification ──")
    total = cur.execute("SELECT COUNT(*) FROM observations").fetchone()[0]

    for col in ["weather_category", "sea_state"]:
        row = cur.execute(f"SELECT COUNT(*) FROM observations WHERE {col} IS NOT NULL").fetchone()
        print(f"  {col}: {row[0]:,} / {total:,} ({row[0]/total*100:.1f}%)")

    print("\n  Weather category distribution:")
    rows = cur.execute("""
        SELECT weather_category, COUNT(*) as cnt
        FROM observations WHERE weather_category IS NOT NULL
        GROUP BY weather_category ORDER BY cnt DESC
    """).fetchall()
    for cat, cnt in rows:
        print(f"    {cat:12s}: {cnt:,}")

    douglas_labels = {
        0: "Calm (glassy)", 1: "Calm (rippled)", 2: "Smooth",
        3: "Slight", 4: "Moderate", 5: "Rough",
        6: "Very rough", 7: "High", 8: "Very high", 9: "Phenomenal",
    }
    print("\n  Sea state distribution (Douglas Scale):")
    rows = cur.execute("""
        SELECT sea_state, COUNT(*) as cnt
        FROM observations WHERE sea_state IS NOT NULL
        GROUP BY sea_state ORDER BY sea_state
    """).fetchall()
    for scale, cnt in rows:
        label = douglas_labels.get(scale, "?")
        print(f"    {scale} ({label:17s}): {cnt:,}")

    # Text records without classification (unmatched terms)
    w_text = cur.execute("SELECT COUNT(*) FROM observations WHERE Weather IS NOT NULL AND Weather != ''").fetchone()[0]
    s_text = cur.execute("SELECT COUNT(*) FROM observations WHERE StateSea IS NOT NULL AND StateSea != ''").fetchone()[0]
    w_null = cur.execute("SELECT COUNT(*) FROM observations WHERE Weather IS NOT NULL AND Weather != '' AND weather_category IS NULL").fetchone()[0]
    s_null = cur.execute("SELECT COUNT(*) FROM observations WHERE StateSea IS NOT NULL AND StateSea != '' AND sea_state IS NULL").fetchone()[0]

    print(f"\n  Unmatched weather: {w_null:,} / {w_text:,} ({w_null/w_text*100:.1f}%)")
    print(f"  Unmatched sea state: {s_null:,} / {s_text:,} ({s_null/s_text*100:.1f}%)")

    conn.close()
    print(f"\nPhase 4 complete. Database: {DB_PATH}")


if __name__ == "__main__":
    main()
